markdown: kramdown
highlighter: rouge
safe: false
lsi: false
exclude: [bin, CNAME, Gemfile, Gemfile.lock]
permalink: /:categories/:title
plugins:
  - jemoji
  - jekyll-redirect-from
sass:
  sass_dir: _sass
