markdown: kramdown
highlighter: rouge
safe: false
lsi: false
exclude: [bin, Gemfile, Gemfile.lock, package.json, yarn.lock,
  postcss.config.js, tailwind.config.js, redirects.json, node_modules]
url: "https://miha.filej.net"
permalink: /:categories/:year/:title
plugins:
  - jekyll-gist
  - jekyll-postcss-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
sass:
  sass_dir: _sass
